# Generated by Django 4.1.7 on 2023-11-07 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0002_alter_video_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="description",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=255,
                verbose_name="description",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(
                default="/video_thumbnail_placeholder.png",
                upload_to="",
                verbose_name="video thumbnail",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.FileField(upload_to="", verbose_name="video"),
        ),
    ]
