# Generated by Django 4.1.7 on 2023-11-08 19:23

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("videos", "0004_alter_video_description_alter_video_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.FileField(
                blank=True,
                default="/video_file_placeholder.png",
                null=True,
                upload_to="",
                verbose_name="video",
            ),
        ),
    ]
