# Generated by Django 4.1.7 on 2023-11-09 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0005_alter_video_tags_alter_video_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.FileField(
                blank=True,
                default="/video_file_placeholder.png",
                null=True,
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "avi", "mkv", "MOV"]
                    )
                ],
                verbose_name="video",
            ),
        ),
    ]
